config/routes.rb
Rails.application.routes.draw do

  resources :categories, except: [:destroy]

  get 'index', to: 'welcome#index'
  get 'about', to: 'welcome#about'

  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'header', to: 'welcome#header'
  
  get 'bills/:id/pay', to: 'bills#pay', as:'pay'
  get 'bills/clear_paid_bills', to: 'bills#clear_paid_bills'
  
  resources :users, except: 'new'
  resources :articles
  resources :bills


  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories

	validates :title, presence: true, length: { minimum: 3, maximum: 100 }
	validates :description, presence: true, length: { minimum: 3, maximum: 3000 }
	validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/bill.rb
class Bill < ActiveRecord::Base

	belongs_to :user

	validates :value, presence: true	

	def self.get_bills(bills)
		bills_hash = {}
		bills_hash['paid'] = bills.where(paid: true)
		bills_hash['not_paid'] = bills.where(paid: false)
		bills_hash
	end
end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :article_categories
	has_many :articles, through: :article_categories

	validates :category_name, presence: true, length: { maximum: 30, minimum: 3 }
	validates_uniqueness_of :category_name
end

app/models/user.rb
class User < ActiveRecord::Base


  has_many :articles, dependent: :destroy
  has_many :bills, dependent: :destroy
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 20 }

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :admin?, :is_admin?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "Please Login"
  		redirect_to root_path
  	end
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = "Not yours"
      redirect_to root_path
    end
  end

  def admin?
    if logged_in?
      is_admin?
    else
      redirect_to root_path  
    end
  end

  def is_admin?
    current_user.role == "admin" if current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_model, only: [ :show, :edit, :update, :destroy ]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
		render 'new'
	end

	def show
	end

	def update
		if @article.update(article_params)
			flash[:success] =  "The Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def create
		@article = Article.new(article_params)	
		@article.user = current_user
		if @article.save
			flash[:success] = "The Article was created."
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end	

	def destroy
		@article.destroy
		flash[:danger] = "Article destroyed"
		redirect_to articles_path
	end

	private

	def article_params
		params.require(:article).permit(:title, :description, category_ids:[])
	end

	def find_model
		@article = Article.find(params[:id]) if params[:id]
	end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  before_action :find_bill, only: [ :show, :pay ]

  def index
    @bills = current_user.bills
    @total = @bills.sum(:value)
    @paid = Bill.get_bills(@bills)['paid']
    @not_paid = Bill.get_bills(@bills)['not_paid']
  end

  def new
    @bill = Bill.new
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.user = current_user
    @bill.paid = false
    if @bill.save
      flash[:success] = "Conta Criada"
      redirect_to bills_path
    else
      flash[:danger] = "Conta não foi Criada"
      render 'new'
    end
  end

  def show
    
  end

  def clear_paid_bills
    paid_bills = current_user.bills.where(paid: true)
    paid_bills.destroy_all
    redirect_to bills_path
  end

  def pay
    @bill.toggle(:paid)
    @bill.save
    redirect_to bills_path
  end

  private

  def bill_params
    params.require(:bill).permit(:bill_name, :description, :value)
  end

  def find_bill
    @bill = Bill.find(params[:id]) if params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :admin?, only: [ :edit, :update ]
	before_action :find_category, only: [ :edit, :update, :show ]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new category_params

		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @category.update category_params
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 4)
	end

	private

	def category_params
		params.require(:category).permit(:category_name)
	end

	def find_category
		@category = Category.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by_email params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome =)"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Sorry, wrong info =("  
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "GoodBye =("
    redirect_to root_path  
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :find_user
	before_action :require_same_user, only: [:edit, :update]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcom #{@user.username}"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		if @user.role == "admin" 
			@user.destroy
			flash[:danger] =  "Destroy"
			redirect_to users_path
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5	)
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated"
			redirect_to articles_path
		else
			render 'edit'
		end
	end


	private

	def user_params
		params.require(:user).permit(:username, :email, :password)		
	end

	def find_user
		@user = User.find(params[:id]) if params[:id]
	end

	def require_same_user
		if current_user != @user
			flash[:danger]= "You can't do this"
			redirect_to root_path
		end
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		redirect_to articles_path if logged_in?		
	end
	
	def about
		
	end

	def header
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle" )
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<hr width="80%;" class="spacer-xs">
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="article-box">
			<div class="article-group">
				<div align="center" class="article-title">
					<%= link_to article.title.humanize, article_path(article), class: 'titulo' %>
				</div>
					<div align="left">
						<% if article.categories.any? %>
								Categories: <%= render article.categories %>
						<% end %>
					</div>
				<div class="article-body">
					<%= truncate(article.description, length: 300) %>
					<div class="article-body-meta">
						<small class="pull-right">Created by <%= article.user.username if article.user %>
							<%= time_ago_in_words(article.updated_at) %> ago
						</small>
					</div>
				</div>
				<div class="article-actions">			
					<div align="right">
						<% if logged_in? && current_user == article.user %>
							<%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
							<%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure?" } ,class: "btn btn-xs btn-danger" %> 
						<% end %>
							<%= link_to "All Articles", articles_path, class: "btn btn-xs btn-success" %> 
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/articles/_article_content.html.erb
    <article>
        <div class="container">
            <div class="row article-content">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h2 class="section-heading"><%= @article.title %></h2>
    <hr>
                    
                    <p><%= simple_format(@article.description) %></p>
                </div>
            </div>
        </div>
    </article>

app/views/articles/_article_header.html.erb
<div>
   <header class="article-header" style="background-image: asset-url('sea_sunset.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1><%= @article.title %></h1>
                    <hr class="small">
                </div>
            </div>
        </div>
    </div>
    </header>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="conatiner">
	<div class="row">
		<div class="col-xs-12">
			<%= form_for( @article, :html => { class: "form-horizontal", role: "form" } ) do |f| %>

			<div class="form-group">
				<div class="control-label-col-sm-2">
					<%= f.label :title %> <br/>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :title, class: "form-control", placeholder: "Articles title", autofocus: true %>
				</div>
			</div>
			<br/>
			<div class="form-group">
				<div class="control-label-col-sm-2">
					<%= f.label :description %> 
				</div>
			</div>
			<div class="col-sm-8">

				<%= f.text_area :description, rows: 5, class: "form-control", placeholder: "Articles title", autofocus: true  %>
			</div>

			<div class="form-group">
			<div class="row">
				<div class="col-sm-offset-2 col-sm-8">
				<%= f.collection_check_boxes :category_ids, Category.all, :id, :category_name do |checkbox|%>
				<%= checkbox.label(class: "checkbox-inline input-checkbox") {checkbox.check_box(class: "checkbox") + checkbox.text} %>
				<% end %>
				</div>				
			</div>
			</div>

			<div class="form-group">
				<div class="col-sm-10">

					<%= f.submit "Save", class: "btn btn-defautl" %>
				</div>
			</div>
			<% end %>

		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="container">
  
  <div class="row center">
    <div class="container index-articles">
      
    <%= will_paginate %>
      <h2 align="center">Artigos Publicados.</h2>
    </div>
  </div>
  <%= link_to 'Escreva o seu próprio artigo!!', new_article_path, class: 'btn btn-primary' %>
  <%= render 'article', obj: @articles %>
  <div class="row center">
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
	
	<h2> Create an Article</h2>
	<%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">

	<%= render 'article_header' %>

	<div class="container">
		
					Categories: <%= render @article.categories %>

		<hr>
			<h4><% if @article.categories.any? %>
					<% end %>
			</h4>
			<hr>
			<%= render 'article_content' %>
			<div class="article-actions">
				<% if current_user == @article.user && logged_in? %>

				<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
				<%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure?" } ,class: "btn btn-xs btn-danger" %> 
				<% end %>
				<%= link_to "All Articles", articles_path, class: "btn btn-xs btn-success" %> 
			</div>
	</div>
</div>

app/views/bills/_bill.html.erb
<h2><%= @bill.bill_name %>
</h2>

app/views/bills/form.html.erb
<h1>Create a new Bill</h1>

app/views/bills/index.html.erb
<div class="container">
  <div class="row">
    <div>
      <h3>Gerênciamento de Contas</h3>
    </div>
  </div>
</div>
</div>
<div class="container">
  <hr>
  <div align="center">
    
    <%= link_to 'Criar uma Conta', new_bill_path, class: 'btn btn-info' %>
    <%= link_to 'Apagar contas pagas', bills_clear_paid_bills_path, class: 'btn btn-danger' %>
  </div>
  <hr>
  <div class="panel panel-success">
    <div class="panel-heading">
      <div class="container">
        <h3 class="panel-title">
          Contas Pagas neste mês
        </h3>
        <div class="container">
          Total: <strong><%= @paid.sum(:value)%></strong>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <table class="table">
        <tr><td><strong>Nome da conta</strong></td>
          <td><strong>Categoria</strong></td>
          <td><strong>Valor</strong></td>
        </tr>
        <% @paid.each do |bill| %>
        <tr>
          <td><%= bill.bill_name %></td>
          <td><%= bill.description %></td>
          <td><%= bill.value %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="panel panel-danger">
    <div class="panel-heading">
      <div class="container">
        <h3 class="panel-title">
          Contas que ainda não foram pagas
        </h3>
        <div class="container">
          Total: <strong><%= @not_paid.sum(:value)%></strong>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <table class="table">
        <tr><td><strong>Nome da conta</strong></td>
          <td><strong>Categoria</strong></td>
          <td><strong>Valor</strong></td>
        </tr>
        <% @not_paid.each do |bill| %>
        <tr>
          <td><%= bill.bill_name %></td>
          <td><%= bill.description %></td>
          <td><%= bill.value %></td>
          <td><%= link_to 'Pay', pay_path(bill) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/bills/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="form-group">
        <div class="col-sm-8">
          <%= form_for( @bill, :html => { class: "form-horizontal", role: "form" } ) do |f| %>
            <div class="form-group">
              <%= f.label 'bill[name]', 'Entre o nome da Conta' %>
              <%= f.text_field :bill_name, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label 'bill[description]', 'Qual a descrição?' %>
              <%= f.text_field :description, class: 'form-control' %>
            </div>

            <div class="form-group">
              <div class="col-sm-2">
                <%= f.label 'bill[value]', 'Valor?' %>
                <%= f.text_field :value, class: 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <%= f.submit 'Criar Conta' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bills/show.html.erb
<div class="container">
<%= render 'bill' %>
</div>

app/views/categories/_category.html.erb
	<span class="badge" > <%= link_to category.category_name, category_path(category), class: 'btn btn-success btn-xs' %>  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<div class="container">
  <div class="col-xs-12">
  <%= form_for( @category, :html => { class: "form-horizontal", role: "form" } ) do |f| %>
    <div class="row">
      <div class="form-group">
        <div class="control-label-col-sm-2">
          <%= f.label :category_name %> <br/>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :category_name, class: "form-control", placeholder: "Category name:", autofocus: true %>
        </div>
      </div>
      <br/>
    </div>
    <div class="form-group">
      <div class="col-sm-10">

        <%= f.submit "Save", class: "btn btn-default" %>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <h2 align="center">Categoria <%= @category.category_name %> em edição</h2>
  </div>
  <hr>
</div>

<div class="container">
  <div class="row">
  <div class="col-xs-10 col-xs-offset-2">
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container">

	<h1 align="center">Categoria do Blog</h1>
	<hr>
	<div class="row center">
		<div class="col-md-8 col-md-offset-2">
		<% @categories.each do |category| %>
			<span class="badge badge-index" > <%= link_to category.category_name, category_path(category), class: 'btn btn-success btn-xs' %>  </span>
		<% end %>
		</div>
	</div>
</div>
<hr>
<div class="container" align="center">
		<%= link_to "Criar nova categoria", new_category_path, class: "btn btn-success" %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
  <div class="col-xs-10 col-xs-offset-2" style="margin-top: 50px;">
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
	<div class="row">
<%= will_paginate @category_articles %>
		<h3> Artigos escritos sobre <strong><%= @category.category_name.capitalize %></strong></h3>
		<%= render 'articles/article', obj: @category_articles %>
	</div>
<%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="https://www.facebook.com/thiagolu">Thiago Lu</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">

	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<% flash.each do |name, msg| %>
				<div class='alert alert-<%="#{ name }"%>'>
					<li><%= msg %></li>
					<a href="#" class="close" data-dismiss="alert">&#215;</a>
					<%= content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String) %>
			</div>
	<% end %>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navigation">
	<div class="container-fluid">
		<%= link_to "Blog", root_path, class: "navbar-brand", id: "logo" %>
		<ul class="nav navbar-nav navbar">
			<li><%=link_to 'Artilces', articles_path %></li>
			<li><%=link_to 'Categories', categories_path %></li>
			<% if logged_in? %>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li><%= link_to "Profile", user_path(current_user) %></li>
					<li><%= link_to "New Article", new_article_path %></li>
					<li role="separator" class="divider"></li>
					<li><%=link_to 'Contas', bills_path %></li>
				</ul>
			</li>
			<% else %>
			<li><%= link_to 'Login', login_path %></li>
			<li><%= link_to 'SignUp', signup_path %></li>
			<% end %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<% if logged_in? %>
			<li><%=link_to 'Logout', logout_path, method: :delete %></li>
			<% end %>
			<li><%= link_to "About", about_path %></li>
		</ul>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FirstBlog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>


	<%= render 'layouts/navigation'%>
	<%= render 'layouts/messages'%>		
	<%= yield %>

	<%= debug(params) if Rails.env.development? %>
	<%= render 'layouts/footer'%>
</body>
</html>

app/views/shared/_errors.html.erb
<div class="container">
	
	<% if obj.errors.any? %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset2">
			<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					Reasons:
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
					
				</div>
			</div>
			</div>
			
		</div>
	</div>
	<h2>The article was not created, fix the following items</h2>
	<% end %>
</div>

app/views/users/_form.html.erb
<div class="conatiner">
<%= render 'shared/errors', obj: @user %>
		<div class="col-xs-12">
			<%= form_for( @user, :html => { class: "form-horizontal", role: "form" } ) do |f| %>

	<div class="row">
			<div class="form-group">
				<div class="control-label-col-sm-2">
					<%= f.label :username %> <br/>
				</div>
				<div class="col-sm-8">
					<%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
				</div>
			</div>
			<br/>
			<div class="form-group">
				<div class="control-label-col-sm-2">
					<%= f.label :email %> 
				</div>
			<div class="col-sm-8">

				<%= f.email_field :email, class: "form-control", placeholder: "Valid@email.address", autofocus: true  %>
			</div>
			</div>
			<div class="form-group">
			<div class="control-label-col-sm-2">
				<%= f.label :password %> 
			</div>
			<div class="col-sm-8">

				<%= f.password_field :password, class: "form-control", placeholder: "EAS@***///|**", autofocus: true  %>
			</div>

			</div>
			<div class="form-group">
				<div class="col-sm-10">

					<%= f.submit "Save", class: "btn btn-default" %>
				</div>
			</div>
			<%= link_to "Home", root_path %>
			<% end %>

		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="row">
	<h2 align="center">Usuários</h2>
	<div align="left" class="container">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well">
				<% @users.each do |user| %>
					<div class="row">
						<br/>
						<%= link_to gravatar_for(user), user_path(user) %>
						<h4><strong><%= user.username.capitalize %></strong></h4>
						<small><%= pluralize(user.articles.count, 'article') if user.articles.any? %></small>
						<% if user.role == 'admin' %>
						<%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are You sure ?" } %>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
<h2>Cadastro de novo usuário</h2>
	
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row center">
    <div class="profile-box">
      <h1>E ae!! <%= @user.username.capitalize %></h1>
      <div>
        <%= gravatar_for @user %>
      </div>
    </div>
    <%= will_paginate @user_articles %>
  </div>
  <hr>
  <h4 align="center"> Estes são os artigos escritos por você:</h4>
  <%= render 'articles/article', obj: @user_articles %>
</div>

app/views/welcome/_header.html.erb
<header id="top" class="header">
	<div class="text-vertical-center">
		<h1>Welcome!</h1>
		<h2>Se tu não faz parte</h2>
		<h3>Sinscrevasse</h3>
		<br>
	  <%= link_to "Sign Up", signup_path, { class: 'btn btn-success' } %>
	  <h4>Caso contrário</h4>
	  <%= link_to 'Faça o Login', login_path, { class: 'btn btn-primary' } %>
	</div>
</header>

app/views/welcome/_listing_articles.html.erb
		<div class="col-xs-6 col-md-4">
			<div class="container">

				<div class="list-group">
					<a href="#" class="list-group-item active">
						<h4 class="list-group-item-heading">Article 1</h4>
						<p class="list-group-item-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 150</p>
					</a>
				</div>
				<div class="list-group">
					<a href="#" class="list-group-item active">
						<h4 class="list-group-item-heading">Article 2</h4>
						<p class="list-group-item-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 150</p>
					</a>
				</div>
				<div class="list-group">
					<a href="#" class="list-group-item active">
						<h4 class="list-group-item-heading">Article 3</h4>
						<p class="list-group-item-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 150</p>
					</a>
				</div>
			</div>
		</div>

app/views/welcome/index.html.erb
  <%= render 'header' %>